apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deploy-{{ include "gocovid.name" . }}
  name: svc-{{ include "gocovid.name" . }}
  namespace: {{ include "namespace" . }}
spec:
  ports:
  - port: {{ .Values.api.port }}
    protocol: TCP
    targetPort: {{ .Values.api.port }}
  selector:
    app: deploy-{{ include "gocovid.name" . }}
  type: NodePort
status:
  loadBalancer: {}
